export const USER_TITLES = [
  // '',
  // 'Dr.',
  // 'Prof.',
  // 'Mr.',
  // 'Ms.',
  // 'Mrs.',
  // 'Mx.',
  // 'Eng.',
  // 'PhD',
  // 'MSc',
  // 'BSc',
  // 'MBA',
  // 'MA',
  { label: 'Select', value: undefined },
  { label: 'Dr.', value: 'Dr.' },
  { label: 'Prof.', value: 'Prof.' },
  { label: 'Mr.', value: 'Mr.' },
  { label: 'Ms.', value: 'Ms.' },
  { label: 'Mrs.', value: 'Mrs.' },
  { label: 'Mx.', value: 'Mx.' },
  { label: 'Eng.', value: 'Eng.' },
  { label: 'PhD', value: 'PhD' },
  { label: 'MSc', value: 'MSc' },
  { label: 'BSc', value: 'BSc' },
  { label: 'MBA', value: 'MBA' },
  { label: 'MA', value: 'MA' },

];
