# name: Test Workflow

# on:
#   push:
#     branches:
#       - main
#       - dev
#   pull_request:
#     branches:
#       - main
#       - dev

# jobs:
#   test:
#     name: Run Tests
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '20'
#           cache: 'npm'

#       - name: Install dependencies
#         run: npm ci

#       - name: Run unit tests
#         run: npm test

#       - name: Upload test coverage
#         uses: actions/upload-artifact@v3
#         with:
#           name: coverage-report
#           path: coverage/
#           if-no-files-found: ignore

#       - name: Install Playwright browsers
#         run: npx playwright install --with-deps

#       - name: Run E2E tests
#         run: npm run test:e2e

#       - name: Upload Playwright report
#         uses: actions/upload-artifact@v3
#         with:
#           name: playwright-report
#           path: playwright-report/
#           if-no-files-found: ignore

#       # Explicitly don't upload test-results directory as it's large and not needed
